apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: openhackakv
spec:
  provider: azure
  secretObjects:
  - secretName: db-user-pass-kv
    data:
    - key: SQL_SERVER
      objectName: SQLSERVER
    - key: SQL_USER
      objectName: SQLUSER
    - key: SQL_PASSWORD
      objectName: SQLPASSWORD 
    type: Opaque
  parameters:
    keyvaultName: "openhackakv"       # The name of the Azure Key Vault
    useVMManagedIdentity: "true"         
    userAssignedIdentityID: "63a15df5-ce19-4982-9be1-c2ec12a2fedd" # The clientId of the addon-created managed identity
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, Azure environment will default to AzurePublicCloud 
    objects:  |
      array:
        - |
          objectName: SQLSERVER       # In this example, 'ExampleSecret'   
          objectType: secret              # Object types: secret, key or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: SQLUSER       # In this example, 'ExampleSecret'   
          objectType: secret              # Object types: secret, key or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: SQLPASSWORD       # In this example, 'ExampleSecret'   
          objectType: secret              # Object types: secret, key or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty        
    tenantId: "8d414110-796b-4038-bdba-db1b0ec43cf9"               # the tenant ID containing the Azure Key Vault instance